name = "birthday-stories"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "birthday-stories-db"
database_id = "db4329e0-f0f7-4843-9845-c4a3e0583144"
